### ISSUE TITLE
IsVoidResult throws `Exception of type 'System.Exception' was thrown`

### ISSUE THREAD

**Issue by ppittle** [Dasync/Dasync#2]
Wired up DAsync against an Azure Service Bus and getting an odd type exceptions.  Is this an infrastructure setup issue or how do I go about starting to troubleshoot this?
```
exceptionMessage:Exception of type 'System.Exception' was thrown.
exceptionType:System.Exception
stacktrace:   at Dasync.Accessors.TaskAccessor.GetTaskResultType(Type taskType)
   at Dasync.Accessors.TaskAccessor.IsVoidResult(Type taskType)
   at Dasync.Accessors.TaskAccessor.IsVoidResult(Task task)
   at Dasync.Serializers.EETypes.TaskSerializer.Decompose(Object value)
   at Dasync.Serialization.ValueContainerSerializer.TryDecomposeValue(Type type, Object value, TypeSerializationInfo& typeInfo, IValueContainer& container)
   at Dasync.Serialization.ValueContainerSerializer.SerializeValue(String name, Type type, Object value, IValueWriter writer, Type collectionItemType, Nullable`1 index)
   at Dasync.Serialization.ValueContainerSerializer.SerializeValueContainer(IValueContainer valueContainer, IValueWriter writer)
   at Dasync.Serialization.ValueContainerSerializer.SerializeValue(String name, Type type, Object value, IValueWriter writer, Type collectionItemType, Nullable`1 index)
   at Dasync.Serialization.ValueContainerSerializer.SerializeValueContainer(IValueContainer valueContainer, IValueWriter writer)
   at Dasync.Serialization.ValueContainerSerializer.Serialize(Object value, IValueWriter writer, IEnumerable`1 specialObjects)
   at Dasync.Serialization.StandardTextSerializer.Serialize(TextWriter writer, Object object)
   at Dasync.Serialization.SerializerExtensions.SerializeToString(ITextSerializer serializer, Object object)
   at Dasync.Serialization.SerializerExtensions.SerializeToString(ISerializer serializer, Object object)
   at SkyKick.Manager.Platform.Dasync.Cache.RoutineStateDto.Create(TransitionType transitionType, SaveStateIntent intent, IPayloadSerializer payloadSerializer, ContinuationDescriptor continuation, Dictionary`2 context, CallerDescriptor caller, String correlationId, String lastTransitionId) in /src/Platform/DasyncFabric/Cache/RoutineStateDto.cs:line 52
   at SkyKick.Manager.Platform.Dasync.Fabric.CommitAsync(ScheduledActions actions, ITransitionCarrier transitionCarrier, TransitionCommitOptions options, CancellationToken ct) in /src/Platform/DasyncFabric/Fabric/Fabric.TransitionCommitter.cs:line 66
   at Dasync.ExecutionEngine.Transitions.TransitionRunner.RunRoutineAsync(ITransitionCarrier transitionCarrier, TransitionDescriptor transitionDescriptor, CancellationToken ct)
   at Dasync.ExecutionEngine.Transitions.TransitionRunner.RunAsync(ITransitionCarrier transitionCarrier, CancellationToken ct)
   at SkyKick.Manager.Platform.Dasync.Fabric.RunCommandAsync(CommandEnvelope envelope, Message message, CancellationToken ct) in /src/Platform/DasyncFabric/Fabric/Fabric.CommandHandler.cs:line 106
   at SkyKick.Manager.Platform.Dasync.Fabric.ProcessCommand(IReceiverClient receiverClient, Message message, CancellationToken ct) in /src/Platform/DasyncFabric/Fabric/Fabric.CommandHandler.cs:line 67
   at SkyKick.Manager.Platform.Dasync.Fabric.ProcessMessage(IReceiverClient receiverClient, Message message, CancellationToken ct) in /src/Platform/DasyncFabric/Fabric/Fabric.ServiceBus.cs:line 123
   at Microsoft.Azure.ServiceBus.MessageReceivePump.MessageDispatchTask(Message message)

```

**Comment by ppittle** [comment]
Problem seems to be [here](https://github.com/Dasync/Dasync/blob/master/Engine/Accessors/TaskAccessor.cs#L154):

```csharp
 public static Type GetTaskResultType(Type taskType)
        {
            /* ... */
            else
            {
                throw new Exception();
            }
        }
```

This is a bit odd - because of the Stack Trace `Dasync.Accessors.TaskAccessor.IsVoidResult(Task task)`, so the incoming type is definitely a `Task` - just not sure why it doesn't match.

Would recommend at least doing this in the iterim:

```csharp
throw new Exception($"Failed to match type [{taskType.FullName}] as a known 'Task' type");
```

**Comment by tyrotoxin** [comment]
Thanks! The fix is available in the new release:
https://www.nuget.org/packages/Dasync.AspNetCore/0.2.9-preview
