### ISSUE TITLE
DAsync support in Asp Core Test Server - Duplicate type name within an assembly

### ISSUE THREAD

**Issue by ppittle** [Dasync/Dasync#4]
I'm getting an exception trying to write an integration test for some additional middleware ontop of DAsync in Asp.Core 2.2. **Using DAsync `0.2.16-preview`**

_Is this scenario supported?_

**Exception Message:**
```csharp
System.ArgumentException : Duplicate type name within an assembly.
   at System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
   at System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
   at System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
   at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent)
   at Dasync.Proxy.ProxyTypeBuilder.BuildType(Type[] interfacesTypes) in C:\Projects\Dasync\Engine\Proxy\ProxyTypeBuilder.cs:line 124
   at Dasync.Proxy.ProxyTypeBuilder.Build(Type baseClass) in C:\Projects\Dasync\Engine\Proxy\ProxyTypeBuilder.cs:line 77
   at Dasync.ExecutionEngine.Proxy.ServiceProxyBuilder.CreateServiceProxy(IServiceDefinition serviceDefinition, String[] additionalInterfaces) in C:\Projects\Dasync\Engine\ExecutionEngine\Proxy\ServiceProxyBuilder.cs:line 53
   at Dasync.ExecutionEngine.Proxy.ServiceProxyBuilder.Build(ServiceId serviceId, String[] additionalInterfaces) in C:\Projects\Dasync\Engine\ExecutionEngine\Proxy\ServiceProxyBuilder.cs:line 43
   at Dasync.ExecutionEngine.Proxy.ServiceProxyBuilder.Build(ServiceId serviceId) in C:\Projects\Dasync\Engine\ExecutionEngine\Proxy\ServiceProxyBuilder.cs:line 35
   at DasyncAspNetCore.ServiceCollectionDasyncExtensions.<>c__DisplayClass3_0.<AddDomainServicesViaDasync>b__0(IServiceProvider serviceProvider) in C:\Projects\Dasync\Fabric\AspNetCore\ServiceCollectionDasyncExtensions.cs:line 60
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at DasyncAspNetCore.DomainServiceProvider.GetService(Type serviceType) in C:\Projects\Dasync\Fabric\AspNetCore\DomainServiceProvider.cs:line 22
   at DasyncAspNetCore.HttpRequestHandler.HandleAsync(PathString basePath, HttpContext context, CancellationToken ct) in C:\Projects\Dasync\Fabric\AspNetCore\HttpRequestHandler.cs:line 305
   at DasyncAspNetCore.DasyncMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Projects\Dasync\Fabric\AspNetCore\DasyncMiddleware.cs:line 29
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
```
**Test Class:**
```csharp
public class TestFixture
{
   [Test]
    public void Test(){
            var builder = new WebHostBuilder()
                .ConfigureAppConfiguration((ctx, config) =>  config)
                .UseStartup<FakeDAsyncServiceStartup>();

            using (var testServer = new TestServer(builder))
            {
                using (var client = testServer.CreateClient())
                {
                    //make call to FakeDAsyncService
               }
          }
 }

public class FakeDAsyncServiceStartup
{
    public FakeDAsyncServiceStartup(IConfiguration configuration)
        {
            Configuration = configuration;
        }
        private IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddPreSharedKeyAuthentication(Configuration)
                .AddHttpClient()
                .AddPlatformHttpClient()
                .AddRouting();

            // Configure D-ASYNC
            services
                .AddDasync(Configuration)
                .AddDomainServicesViaDasync(FakeDAsyncServiceModel.Instance);

            services.Rebind<ICommunicationModelProvider>().To(new CommunicationModelProvider(
                new CommunicationModelProvider.Holder { Model = FakeDAsyncServiceModel.Instance }));

            services.AddDevelopmentFabricForDasync(Configuration);
       }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
             var communicationModel = app.ApplicationServices.GetService<ICommunicationModelProvider>().Model;
            app.UseDasync(communicationModel);
        }
}

**Comment by tyrotoxin** [comment]
@ppittle, thanks, this must be fixed in [v0.2.17](https://www.nuget.org/packages/Dasync.AspNetCore/0.2.17-preview).
Most likely there are two test assemblies which define services with same names.

**Comment by tyrotoxin** [comment]
@ppittle, FYI, with the latest release, most likely you'll need to adjust namespace usings in few spots. Few DI-related extension methods moved to `Dasync.DependencyInjection`.

**Comment by ppittle** [comment]
@kind-serge - confirmed upgrading fixed my issue.  Testing my asp core middleware on-top of dasync using `TestServer` worked great!
