### ISSUE TITLE
Dasync fails to disambiguate between identically named code block scoped variables

### ISSUE THREAD

**Issue by mhintzke** [Dasync/Dasync#7]
Given a situation like below where 2 code blocks both contain a variable declaration of the same name, `foo`, the Dasync framework attempts to re-saturate the execution context following the `await`ed method (`Task.Delay(1)` which symbolizes any async IO requiring a Dasync transition):

```c#
public class Example
{
    public async void Test()
    {
        var boolean = true;

        if (boolean)
        {
            var foo = "hello";
            await Task.Delay(1);

            Console.WriteLine(foo);
        }
        else
        {
            var foo = "world";
            await Task.Delay(1);

            Console.WriteLine(foo);
        }
    }
}
```

During the execution of a method like this, Dasync fails to disambiguate between the 2 distinct variables in each code block and throws this exception:

```
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetField(String name, BindingFlags bindingAttr)
   at Dasync.ValueContainer.ValueContainerTypeBuilder.BuildInternal(ContainerDesc desc)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Dasync.ValueContainer.ValueContainerTypeBuilder.Build(Type delegatedType, IEnumerable`1 delegatedProperties, String newTypeName)
   at Dasync.ValueContainer.ValueContainerFactory.CreateProxy(Object target, IEnumerable`1 properties)
   at Dasync.ExecutionEngine.Transitions.TransitionRunner.GetValueContainerProxy(IAsyncStateMachine asyncStateMachine, AsyncStateMachineMetadata metadata)
   at Dasync.ExecutionEngine.Transitions.TransitionRunner.LoadRoutineStateAsync(ITransitionCarrier transitionCarrier, IAsyncStateMachine asyncStateMachine, AsyncStateMachineMetadata metadata, Boolean isContinuation, CancellationToken ct)
   at Dasync.ExecutionEngine.Transitions.TransitionRunner.RunRoutineAsync(ITransitionCarrier transitionCarrier, TransitionDescriptor transitionDescriptor, CancellationToken ct)
   at Dasync.ExecutionEngine.Transitions.TransitionRunner.RunAsync(ITransitionCarrier transitionCarrier, CancellationToken ct)
... application code stack trace
```
If this has been fixed in newer versions of Dasync then we can gladly close it as solved.  There are workarounds that one could say results in better design anyways like moving the scope of the variable above both code blocks or using 2 different names, but there could still be valid reasons to do this and since the C# compiler allows this scenario it seems like it should be supported nonetheless.

**Comment by kind-serge** [comment]
Thanks for reporting this, @mhintzke, and it's a known issue.

**Why It Happens.**
The C# compiler generates a state machine similar to this:
```csharp
class Test_StateMachine
{
  Example __this;
  int __state;
  string <foo>__1;
  string <foo>__2;
}
```
Notice that both variables `foo` get compiled into two fields with non-CLS-compliant names enclosed into angular brackets. D-ASYNC engine uses the name inside the brakets for the human-readable (deggable) JSON serialization, e.g.:
```json
{
  "foo": "hello"
}
```
Since there are two logical variables with the same name, it won't be possible to serialize into a friendly JSON form.

**Known Workaround.**
As you already mentioned, there are 2 options: name variables differently or declare a single variable outside the code blocks.

**Future Work.**
1. The interim solution would be the use of original compiler-generated names for the serialization.
2. The long-term plan is to have a full analysis of the state machine states and transitions, and their relationship to the used variables. In that example, a variable exists in a certain scope and will never be used again in other state machine transitions and states. Such knowledge will guide serializer to use the proper field(s) of the generated state machine.

**Comment by zammitt** [comment]
In the short term, could you handle the AmbiguousMatchException exception and surface it as an error explaining the problem?

**Comment by mhintzke** [comment]
@kind-serge I assumed it was a known issue but just wanted to confirm so thanks!

The issue definitely makes sense and the workaround is easy enough to mitigate the problems in the interim.  As @zammitt suggested, would it at all be possible to make a patch fix to beta version of Dasync in order to make this exception more understandable to future developers? If not, we will do our best to share the knowledge and keep a lookout for it.
